export const env = {
    NOTION_API_KEY: process.env.NOTION_API_KEY,
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,

    // Database Tokens
    NOTION_DB_DISPENSARY_MASTER: process.env.NOTION_DB_DISPENSARY_MASTER,
    NOTION_DB_MEETING_NOTES: process.env.NOTION_DB_MEETING_NOTES,
    NOTION_DB_VENDOR_EVENTS: process.env.NOTION_DB_VENDOR_EVENTS,
    NOTION_DB_PENNY_BUNDLES: process.env.NOTION_DB_PENNY_BUNDLES,
    NOTION_DB_CONTACTS: process.env.NOTION_DB_CONTACTS,
    NOTION_DB_PICC_DIRECTORY: process.env.NOTION_DB_PICC_DIRECTORY,
    NOTION_DB_MASTER_SALES: process.env.NOTION_DB_MASTER_SALES,
};
