import React, { useState } from 'react';
import { generatePlatformOptimizations } from '../services/geminiService';
import { ShieldCheck, Sparkles, Database, Loader2, ArrowRight, LayoutTemplate, Zap, Search } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';

export const AdminDashboard: React.FC = () => {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const searchData = [
    { term: 'Commission', count: 145 },
    { term: 'Wellness', count: 120 },
    { term: 'Expense Policy', count: 98 },
    { term: 'PPP Status', count: 85 },
    { term: 'Q3 Playbook', count: 72 },
  ];

  const handleRunAnalysis = async () => {
    setIsAnalyzing(true);
    const result = await generatePlatformOptimizations();
    setAnalysis(result);
    setIsAnalyzing(false);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <ShieldCheck className="text-indigo-600" /> Platform Admin
          </h1>
          <p className="text-slate-500 mt-1">Monitor workspace health and optimize UX based on intelligence.</p>
        </div>
        <div className="flex items-center gap-2 px-3 py-1 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-full text-xs font-medium">
            <Database size={14} /> Notion Connected: Active
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Col: Controls & Stats */}
        <div className="space-y-6">
            
            {/* Action Card */}
            <div className="bg-gradient-to-br from-indigo-900 to-indigo-800 rounded-2xl p-6 text-white shadow-lg relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-white opacity-5 rounded-full -mr-10 -mt-10" />
                <h2 className="text-lg font-bold mb-2 flex items-center gap-2">
                    <Sparkles size={18} className="text-yellow-300" /> AI Platform Audit
                </h2>
                <p className="text-indigo-200 text-sm mb-6">
                    Analyze connected Notion pages, meeting notes, and search logs to identify UX bottlenecks and suggest structural improvements.
                </p>
                <button 
                    onClick={handleRunAnalysis}
                    disabled={isAnalyzing}
                    className="w-full bg-white text-indigo-900 font-semibold py-3 rounded-lg flex items-center justify-center gap-2 hover:bg-indigo-50 transition-colors disabled:opacity-80"
                >
                    {isAnalyzing ? <Loader2 className="animate-spin" /> : <Zap size={18} />}
                    {isAnalyzing ? 'Thinking...' : 'Analyze Workspace'}
                </button>
            </div>

            {/* Search Trends */}
            <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                <h3 className="font-semibold text-slate-800 mb-4 flex items-center gap-2">
                    <Search size={16} className="text-slate-400" /> Top Failed Searches
                </h3>
                <div className="h-48 text-xs">
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={searchData} layout="vertical">
                            <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f1f5f9" />
                            <XAxis type="number" hide />
                            <YAxis dataKey="term" type="category" width={90} tick={{fontSize: 11, fill: '#64748b'}} />
                            <Tooltip cursor={{fill: 'transparent'}} contentStyle={{borderRadius: '8px'}} />
                            <Bar dataKey="count" fill="#6366f1" radius={[0, 4, 4, 0]} barSize={20} />
                        </BarChart>
                    </ResponsiveContainer>
                </div>
            </div>
        </div>

        {/* Right Col: Analysis Results */}
        <div className="lg:col-span-2">
            <div className="bg-white rounded-xl border border-slate-200 min-h-[500px] shadow-sm flex flex-col">
                <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                    <h3 className="font-bold text-slate-800 flex items-center gap-2">
                        <LayoutTemplate size={18} className="text-slate-500" /> Optimization Suggestions
                    </h3>
                    {analysis && <span className="text-xs text-slate-400">Generated by Gemini 3 Pro</span>}
                </div>
                
                <div className="p-6 flex-1 bg-slate-50/50">
                    {!analysis && !isAnalyzing && (
                        <div className="h-full flex flex-col items-center justify-center text-slate-400 text-center p-8">
                            <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
                                <Sparkles size={32} className="text-slate-300" />
                            </div>
                            <p className="max-w-md">Run the audit to see AI-generated suggestions for improving the platform structure based on your live Notion data.</p>
                        </div>
                    )}

                    {isAnalyzing && (
                         <div className="h-full flex flex-col items-center justify-center text-indigo-600 text-center p-8 animate-pulse">
                            <div className="w-16 h-16 bg-indigo-50 rounded-full flex items-center justify-center mb-4">
                                <Zap size={32} />
                            </div>
                            <h4 className="font-semibold text-lg">Analyzing Patterns...</h4>
                            <p className="text-sm text-indigo-400 mt-2 max-w-md">Reading meeting notes, policies, and feedback logs to identify structural opportunities.</p>
                        </div>
                    )}

                    {analysis && (
                        <div className="prose prose-sm prose-indigo max-w-none">
                            <div className="whitespace-pre-wrap">{analysis}</div>
                            
                            <div className="mt-8 pt-6 border-t border-slate-200">
                                <h4 className="text-xs font-bold text-slate-400 uppercase mb-3">Suggested Actions</h4>
                                <div className="flex gap-3">
                                    <button className="px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium hover:border-indigo-300 text-slate-700">Export Report</button>
                                    <button className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-medium hover:bg-indigo-700 flex items-center gap-2">
                                        Apply Changes <ArrowRight size={14} />
                                    </button>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};
